// Barrel: re-export all UI primitives.
// Feature code imports from "@/components/ui".
export { BentoTile } from "./bento-tile";
export { Bars } from "./bars";
export { Badge, Badge as Pill } from "./badge";
export { Button } from "./button";
export { useFocusTrap } from "./use-focus-trap";
export { Card } from "./card";
export { Checkbox } from "./checkbox";
export { ContributionHeatmap } from "./contribution-heatmap";
export { Delta } from "./delta";
export { Field, Input } from "./input";
export { ItemEvidence } from "./item-evidence";
export { Label, Label as MonoLabel } from "./label";
export { PageHeader } from "./page-header";
export { Reveal } from "./reveal";
export { Section } from "./section";
export { Select } from "./select";
export { SegmentedControl } from "./segmented-control";
export { FilterChip } from "./filter-chip";
export { InsightRow } from "./insight-row";
export { FillStrip } from "./fill-strip";
export { IconButton } from "./icon-button";
export { Avatar, initialsOf } from "./avatar";
export { PacedBar, yearElapsedPercent } from "./paced-bar";
export { ProgressRing } from "./progress-ring";
export { Sparkline } from "./sparkline";
export { LineSpark } from "./line-spark";
export { StarGlyph } from "./star-glyph";
export { Stat } from "./stat";
export { TileState } from "./tile-state";
export { Loader, Loading } from "./loader";
