"use client";

import { ExternalLink } from "lucide-react";
import { Badge, Card, Label } from "@/components/ui";
import { useIntegrations } from "@/features/integrations";
import { formatExpected } from "./format-expected";

const STATUS_TONE = { ok: "mint", accent: "lav", warn: "peach", muted: "neutral" };

const TIER_SHORT = {
  not_achieved: "Not met",
  achieved: "Achieved",
  over_achieved: "Over-achieved",
  role_model: "Role model",
};

/** Short calendar date for an evidence timestamp — the "when". */
function fmtDate(ts) {
  if (!ts) return "";
  return new Date(ts).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

export function DocumentPreview({
  format,
  level,
  narrative,
  setNarrative,
  include,
  goalReadings,
  starred,
  rangeLabel,
}) {
  const { me } = useIntegrations();

  const filename = `performance-review-ytd.${format === "markdown" ? "md" : "pdf"}`;

  const showStarred =
    include.starred !== false && Array.isArray(starred) && starred.length > 0;
  const sectionCount =
    (include.narrative ? 1 : 0) +
    (include.goals && goalReadings && goalReadings.length > 0 ? 1 : 0) +
    (showStarred ? 1 : 0);

  return (
    <Card padding={0}>
      <div className="flex items-center justify-between border-b border-line px-5 py-3">
        <Label>Document preview · {filename}</Label>
        <Label>
          {sectionCount} section{sectionCount === 1 ? "" : "s"}
        </Label>
      </div>

      <div className="min-h-[640px] p-7">
        <div className="text-[22px] font-bold tracking-[-0.01em] leading-[1.15] text-fg">
          {me?.name ?? "Your name"} — {me?.team ?? "—"}
        </div>
        <div className="mt-1 text-[13px] text-muted-fg">
          Level {level} · {rangeLabel}
        </div>
        <div className="my-4 border-t border-line" aria-hidden="true" />

        {include.narrative ? (
          <DocSection title="Summary" rangeLabel={rangeLabel}>
            <textarea
              value={narrative}
              onChange={(e) => setNarrative(e.target.value)}
              rows={5}
              placeholder="A few sentences on what this window meant for your goals — what moved, what stalled, what's next. The per-goal readings below are the receipts; this is the throughline."
              className="w-full resize-y rounded-[var(--radius-lg)] bg-card-alt p-3 text-[14.5px] leading-[1.6] text-fg outline-none placeholder:text-dim-fg focus:ring-2 focus:ring-ink"
            />
            <div className="mt-1 text-[12px] text-dim-fg">Click to edit · your words, not ours</div>
          </DocSection>
        ) : null}

        {include.goals && goalReadings && goalReadings.length > 0 ? (
          <DocSection
            title={`Performance goals · ${countL1(goalReadings)} L1 · ${countL2(goalReadings)} L2`}
            rangeLabel="AI-classified · live"
          >
            <GoalReadingsBlock readings={goalReadings} />
          </DocSection>
        ) : null}

        {showStarred ? (
          <DocSection title={`Starred proof · ${starred.length}`} rangeLabel="Hand-picked">
            <ul className="flex flex-col gap-1.5">
              {starred.map((s) => (
                <li key={s.id} className="flex items-baseline gap-2 text-[13px] leading-[1.45] text-fg">
                  {s.ref ? <span className="shrink-0 font-mono font-bold text-muted-fg">{s.ref}</span> : null}
                  <span className="min-w-0">
                    {s.title || "(untitled)"}
                    {s.impact?.trim() ? <span className="text-muted-fg"> — {s.impact.trim()}</span> : null}
                  </span>
                  {s.date ? <span className="ml-auto shrink-0 text-dim-fg">{s.date}</span> : null}
                </li>
              ))}
            </ul>
          </DocSection>
        ) : null}

        <div className="mt-10 flex justify-between border-t border-line pt-4 text-[12px] text-dim-fg">
          <span>
            Generated by eSpace Hubs ·{" "}
            {new Date().toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
              year: "numeric",
            })}
          </span>
          <span>Source: your logged goal evidence</span>
        </div>
      </div>
    </Card>
  );
}

function DocSection({ title, rangeLabel, children }) {
  return (
    <div className="mb-3.5 mt-6">
      <div className="mb-2 flex items-baseline justify-between gap-3">
        <h3 className="m-0 text-[15px] font-bold text-fg">{title}</h3>
        <span className="text-[12px] text-dim-fg">{rangeLabel}</span>
      </div>
      {children}
    </div>
  );
}

/**
 * Renders the AI-classified goal tree with each L2's current widget
 * reading. Sorted by L1 → L2 in the original onboarding order.
 */
function GoalReadingsBlock({ readings }) {
  // Group by L1: each row is either an L1 (level === "L1") or an L2 with
  // parentL1 set. Walk in original order; emit an L1 header card every
  // time we see a new L1 group.
  const grouped = [];
  let currentGroup = null;
  for (const r of readings) {
    if (r.level === "L1") {
      currentGroup = { l1: r, items: [] };
      grouped.push(currentGroup);
    } else if (r.level === "L2") {
      // If the L2 belongs to an L1 we haven't created a header for (because
      // the L1 wasn't classified), spin up a header from the parent goal
      // alone — keeps the tree readable.
      const expectedL1Id = r.parentL1?.id;
      if (!currentGroup || currentGroup.l1.goal.id !== expectedL1Id) {
        currentGroup = {
          l1: { goal: r.parentL1, spec: null, reading: null, level: "L1" },
          items: [],
        };
        grouped.push(currentGroup);
      }
      currentGroup.items.push(r);
    }
  }

  // Per-goal blocks (what / how / when) — mirrors the exported PDF/markdown so
  // the on-screen preview never shows less than the download.
  return (
    <div className="flex flex-col gap-5">
      {grouped.map((g, gi) => (
        <div key={(g.l1.goal && g.l1.goal.id) || gi}>
          <div className="flex items-baseline justify-between gap-3 border-b border-line pb-1.5">
            <span className="min-w-0 truncate text-[14px] font-bold text-fg" title={g.l1.goal?.title}>
              {g.l1.goal?.title || "(untitled L1)"}
              {g.l1.goal?.weightage > 0 ? (
                <span className="ml-2 text-[12px] font-normal text-dim-fg">{g.l1.goal.weightage}% weight</span>
              ) : null}
            </span>
            {g.l1.reading ? (
              <span className="shrink-0 text-[12px] text-muted-fg">{g.l1.reading.value}</span>
            ) : null}
          </div>
          {g.items.length === 0 ? (
            <div className="mt-2 text-[13px] text-dim-fg">No L2s classified yet for this L1.</div>
          ) : (
            <div className="mt-2.5 flex flex-col gap-3">
              {g.items.map((r) => (
                <PreviewGoalBlock key={r.goal.id} r={r} />
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

/** One L2 goal in the paper preview: target → achieved (+ tier), the grader's
 *  assessment, and the dated evidence. Mirrors the PDF's GoalBlock. */
function PreviewGoalBlock({ r }) {
  const v = r.verdict;
  const graded = v && !v.awaiting && !v.pendingSetup;
  const tier = graded && v.tier ? TIER_SHORT[v.tier] : null;
  const reasoning = graded && v.reasoning ? v.reasoning : null;
  const expected = formatExpected(r.spec);
  const evidence = Array.isArray(r.evidence) ? r.evidence : [];

  return (
    <div className="border-l-2 border-line pl-3">
      <div className="flex items-start justify-between gap-2">
        <span className="min-w-0 text-[13.5px] font-semibold text-fg" title={r.goal.title}>
          {r.goal.title || "(untitled L2)"}
        </span>
        <div className="flex shrink-0 items-center gap-1.5">
          {tier ? <Badge tone="lav">{tier}</Badge> : null}
          {r.reading?.statusLabel ? (
            <Badge tone={STATUS_TONE[r.reading.statusTone] || "neutral"}>{r.reading.statusLabel}</Badge>
          ) : null}
        </div>
      </div>
      <div className="mt-1 text-[12.5px] text-muted-fg">
        <span className="text-dim-fg">Target </span>
        {expected || "—"}
        <span className="text-dim-fg">  →  Achieved </span>
        {r.reading?.value || "—"}
      </div>
      {reasoning ? (
        <div className="mt-1 text-[12.5px] leading-[1.45] text-fg">
          <span className="text-dim-fg">Assessment </span>
          {reasoning}
          {v.confidence === "low" ? <span className="text-dim-fg"> · low confidence</span> : null}
        </div>
      ) : null}
      {evidence.length ? (
        <ul className="mt-1.5 flex flex-col gap-1">
          {evidence.map((ev, i) => (
            <li key={i} className="flex items-start gap-2 text-[12px] leading-[1.4] text-fg">
              <span className="mt-px shrink-0 text-dim-fg" style={{ width: 40 }}>
                {fmtDate(ev.ts)}
              </span>
              <span className="min-w-0">
                {ev.text}
                {ev.url ? (
                  <>
                    {" "}
                    <a
                      href={ev.url}
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center gap-1 font-bold text-fg hover:underline"
                    >
                      <ExternalLink size={11} />
                    </a>
                  </>
                ) : null}
              </span>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}

function countL1(readings) {
  return readings.filter((r) => r.level === "L1").length;
}
function countL2(readings) {
  return readings.filter((r) => r.level === "L2").length;
}
