"use client";

import { ExternalLink } from "lucide-react";
import { Badge, Card, Label, ValueSkeleton } from "@/components/ui";
import { formatExpected } from "./format-expected";
import { documentTitle, goalCountLine } from "./markdown-export";

const TIER_SHORT = {
  not_achieved: "Not met",
  achieved: "Achieved",
  over_achieved: "Over-achieved",
  role_model: "Role model",
};

/** Short calendar date for an evidence timestamp — the "when". */
function fmtDate(ts) {
  if (!ts) return "";
  return new Date(ts).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

export function DocumentPreview({
  name,
  team,
  untracked = [],
  filename = "performance-review",
  level,
  narrative,
  setNarrative,
  include,
  goalReadings,
  starred,
  rangeLabel,
}) {
  const untrackedRows = include.goals ? (untracked || []).filter(Boolean) : [];
  const showStarred =
    include.starred !== false && Array.isArray(starred) && starred.length > 0;
  const sectionCount =
    (include.narrative ? 1 : 0) +
    (include.goals && goalReadings && goalReadings.length > 0 ? 1 : 0) +
    (untrackedRows.length > 0 ? 1 : 0) +
    (showStarred ? 1 : 0);

  return (
    <Card padding={0}>
      <div className="flex items-center justify-between border-b border-line px-5 py-3">
        <Label>Document preview · {filename}</Label>
        <Label>
          {sectionCount} section{sectionCount === 1 ? "" : "s"}
        </Label>
      </div>

      <div className="min-h-[640px] p-7">
        {/* The account's name (Settings → Account), not a provider login —
            a document with no name read "Your name — —". */}
        <h2 className="m-0 text-[22px] font-bold tracking-[-0.01em] leading-[1.15] text-fg">
          {documentTitle(name, level)}
        </h2>
        <div className="mt-1 text-[13px] text-muted-fg">
          {[team, rangeLabel].filter(Boolean).join(" · ")}
        </div>
        <div className="my-4 border-t border-line" aria-hidden="true" />

        {include.narrative ? (
          <DocSection title="Summary" rangeLabel={rangeLabel}>
            <textarea
              value={narrative}
              onChange={(e) => setNarrative(e.target.value)}
              rows={5}
              placeholder="A few sentences on what this window meant for your goals — what moved, what stalled, what's next. The per-goal readings below are the receipts; this is the throughline."
              className="w-full resize-y rounded-[var(--radius-lg)] bg-card-alt p-3 text-[14.5px] leading-[1.6] text-fg border border-field-line outline-none placeholder:text-dim-fg focus:ring-2 focus:ring-ink"
            />
            <div className="mt-1 text-[12px] text-muted-fg">
              Your words, not ours · Draft saved on this device only
            </div>
          </DocSection>
        ) : null}

        {include.goals && goalReadings && goalReadings.length > 0 ? (
          <DocSection
            title={`Performance goals · ${goalCountLine(goalReadings)}`}
            rangeLabel="Live"
          >
            <GoalReadingsBlock readings={goalReadings} />
          </DocSection>
        ) : null}

        {untrackedRows.length > 0 ? (
          <DocSection title={`Not yet tracked (${untrackedRows.length})`} rangeLabel="Not in any number">
            <p className="m-0 mb-2 text-[13px] text-muted-fg">
              These goals have no tracker yet. The packet lists them so your manager sees the
              whole year.
            </p>
            <ul className="m-0 flex list-disc flex-col gap-1 pl-5">
              {untrackedRows.map((g) => (
                <li key={g.id} className="text-[13px] leading-[1.45] text-fg">
                  {g.title || "(untitled goal)"}
                </li>
              ))}
            </ul>
          </DocSection>
        ) : null}

        {showStarred ? (
          <DocSection title={`Starred proof · ${starred.length}`} rangeLabel="Hand-picked">
            <ul className="flex flex-col gap-1.5">
              {starred.map((s) => (
                <li key={s.id} className="flex items-baseline gap-2 text-[13px] leading-[1.45] text-fg">
                  {s.ref ? <span className="shrink-0 font-mono font-bold text-muted-fg">{s.ref}</span> : null}
                  <span className="min-w-0">
                    {s.title || "(untitled)"}
                    {s.impact?.trim() ? <span className="text-muted-fg"> — {s.impact.trim()}</span> : null}
                  </span>
                  {s.date ? <span className="ml-auto shrink-0 text-muted-fg">{s.date}</span> : null}
                </li>
              ))}
            </ul>
          </DocSection>
        ) : null}

        <div className="mt-10 flex justify-between border-t border-line pt-4 text-[12px] text-muted-fg">
          <span>
            Generated by eSpace Hubs ·{" "}
            {new Date().toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
              year: "numeric",
            })}
          </span>
          <span>Source: your logged goal evidence</span>
        </div>
      </div>
    </Card>
  );
}

function DocSection({ title, rangeLabel, children }) {
  return (
    <div className="mb-3.5 mt-6">
      <div className="mb-2 flex items-baseline justify-between gap-3">
        <h3 className="m-0 text-[15px] font-bold text-fg">{title}</h3>
        <span className="text-[12px] text-muted-fg">{rangeLabel}</span>
      </div>
      {children}
    </div>
  );
}

/**
 * Renders the AI-classified goal tree with each L2's current widget
 * reading. Sorted by L1 → L2 in the original onboarding order.
 */
function GoalReadingsBlock({ readings }) {
  // Group by L1: each row is either an L1 (level === "L1") or an L2 with
  // parentL1 set. Walk in original order; emit an L1 header card every
  // time we see a new L1 group.
  const grouped = [];
  let currentGroup = null;
  for (const r of readings) {
    if (r.level === "L1") {
      currentGroup = { l1: r, items: [] };
      grouped.push(currentGroup);
    } else if (r.level === "L2") {
      // If the L2 belongs to an L1 we haven't created a header for (because
      // the L1 wasn't classified), spin up a header from the parent goal
      // alone — keeps the tree readable.
      const expectedL1Id = r.parentL1?.id;
      if (!currentGroup || currentGroup.l1.goal.id !== expectedL1Id) {
        currentGroup = {
          l1: { goal: r.parentL1, spec: null, reading: null, level: "L1" },
          items: [],
        };
        grouped.push(currentGroup);
      }
      currentGroup.items.push(r);
    }
  }

  // Per-goal blocks (what / how / when) — mirrors the exported PDF/markdown so
  // the on-screen preview never shows less than the download.
  return (
    <div className="flex flex-col gap-5">
      {grouped.map((g, gi) => (
        <div key={(g.l1.goal && g.l1.goal.id) || gi}>
          <div className="flex items-baseline justify-between gap-3 border-b border-line pb-1.5">
            <h4 className="m-0 min-w-0 truncate text-[14px] font-bold text-fg" title={g.l1.goal?.title}>
              {g.l1.goal?.title || "(untitled objective)"}
              {g.l1.goal?.weightage > 0 ? (
                <span className="ml-2 text-[12px] font-normal text-muted-fg">Weight {g.l1.goal.weightage}%</span>
              ) : null}
            </h4>
            {g.l1.reading ? (
              <span className="shrink-0 text-[12px] text-muted-fg">
                <AchievedValue reading={g.l1.reading} />
              </span>
            ) : null}
          </div>
          {g.items.length === 0 ? (
            <div className="mt-2 text-[13px] text-muted-fg">No goals with a tracker under this objective yet.</div>
          ) : (
            <div className="mt-2.5 flex flex-col gap-3">
              {g.items.map((r) => (
                <PreviewGoalBlock key={r.goal.id} r={r} />
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

/** One L2 goal in the paper preview: target → achieved (+ tier), the grader's
 *  assessment, and the dated evidence. Mirrors the PDF's GoalBlock. */
function PreviewGoalBlock({ r }) {
  const v = r.verdict;
  const graded = v && !v.awaiting && !v.pendingSetup;
  const tier = graded && v.tier ? TIER_SHORT[v.tier] : null;
  const reasoning = graded && v.reasoning ? v.reasoning : null;
  const expected = formatExpected(r.spec);
  const evidence = Array.isArray(r.evidence) ? r.evidence : [];

  return (
    <div className="border-l-2 border-line pl-3">
      <div className="flex items-start justify-between gap-2">
        <span className="min-w-0 text-[13.5px] font-semibold text-fg" title={r.goal.title}>
          {r.goal.title || "(untitled goal)"}
        </span>
        <div className="flex shrink-0 items-center gap-1.5">
          {tier ? <Badge tone="lav">{tier}</Badge> : null}
          {r.reading?.statusLabel ? (
            <Badge tone={r.reading.statusTone || "neutral"} title={r.reading.statusReason || undefined}>
              {r.reading.statusLabel}
            </Badge>
          ) : null}
        </div>
      </div>
      <div className="mt-1 text-[12.5px] text-muted-fg">
        <span className="text-muted-fg">Target </span>
        {expected || "—"}
        <span className="text-muted-fg">  →  Achieved </span>
        <AchievedValue reading={r.reading} />
      </div>
      {reasoning ? (
        <div className="mt-1 text-[12.5px] leading-[1.45] text-fg">
          <span className="text-muted-fg">Assessment </span>
          {reasoning}
          {v.confidence === "low" ? <span className="text-muted-fg"> · low confidence</span> : null}
        </div>
      ) : null}
      {evidence.length ? (
        <ul className="mt-1.5 flex flex-col gap-1">
          {evidence.map((ev, i) => (
            <li key={i} className="flex items-start gap-2 text-[12px] leading-[1.4] text-fg">
              <span className="mt-px shrink-0 text-muted-fg" style={{ width: 40 }}>
                {fmtDate(ev.ts)}
              </span>
              <span className="min-w-0">
                {ev.text}
                {ev.url ? (
                  <>
                    {" "}
                    <a
                      href={ev.url}
                      target="_blank"
                      rel="noreferrer"
                      aria-label="Open the linked evidence in a new tab"
                      title="Open the linked evidence"
                      className="inline-flex items-center gap-1 font-bold text-fg hover:underline"
                    >
                      <ExternalLink size={11} aria-hidden="true" />
                    </a>
                  </>
                ) : null}
              </span>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}


/**
 * The achieved value in the preview. A PR-derived reading whose feed hasn't
 * answered is a skeleton (never "0 merged"); one standing in from the
 * widget's last published reading says so; an unavailable feed says why.
 */
function AchievedValue({ reading }) {
  if (!reading) return "—";
  if (reading.pending) return <ValueSkeleton className="w-[8ch]" label="Loading the reading" />;
  if (reading.unavailable) return <span className="text-peach-text">{reading.value}</span>;
  return (
    <>
      {reading.value || "—"}
      {reading.lastKnown ? (
        <span className="text-muted-fg" title="Your code host hasn't answered yet — this is the last value the goal showed.">
          {" "}· last known
        </span>
      ) : null}
    </>
  );
}
