/**
 * Pure rendering — builds the Markdown string for the evidence export.
 * Separated from UI so it can be unit-tested and reused for PDF.
 */

import { formatExpected } from "./format-expected";

export function renderMarkdown({
  name,
  team,
  level,
  rangeLabel,
  narrative,
  goalReadings,
  include = { narrative: true, goals: true },
}) {
  const lines = [];
  lines.push(`# ${name ?? "—"} — ${level ?? "Performance review"}`);
  lines.push(`_${team ?? ""} · ${rangeLabel ?? ""}_`);
  lines.push("");

  if (include.narrative && narrative?.trim()) {
    lines.push("## 01 · Summary");
    lines.push(narrative.trim());
    lines.push("");
  }

  if (include.goals && Array.isArray(goalReadings) && goalReadings.length > 0) {
    const l1s = goalReadings.filter((r) => r.level === "L1").length;
    const l2s = goalReadings.filter((r) => r.level === "L2").length;
    lines.push(`## 02 · Performance goals · ${l1s} L1 · ${l2s} L2`);
    // Group L1 → its L2s. Each L1 gets its own Expected/Achieved table
    // for that L1's children. Reads more like a structured perf-review
    // packet than a list of bullets — the markdown table headers become
    // proper columns when rendered.
    let activeL1 = null;
    let pendingHeader = false;
    function emitTableHeader() {
      lines.push("");
      lines.push("| Goal | Expected | Achieved | Status |");
      lines.push("|---|---|---|---|");
      pendingHeader = false;
    }
    for (const r of goalReadings) {
      if (r.level === "L1") {
        activeL1 = r;
        const w = r.goal?.weightage > 0 ? ` _(${r.goal.weightage}% weight)_` : "";
        lines.push("");
        lines.push(`### ${r.goal?.title || "(untitled L1)"}${w}`);
        if (r.reading) {
          lines.push("");
          lines.push(`> ${r.reading.value} — _${r.reading.statusLabel}_`);
        }
        // Defer the table header until we see the first L2 (avoids
        // empty tables for L1s with no classified children).
        pendingHeader = true;
      } else if (r.level === "L2") {
        if (!activeL1 || activeL1.goal?.id !== r.parentL1?.id) {
          activeL1 = { goal: r.parentL1, level: "L1", reading: null };
          const w =
            r.parentL1?.weightage > 0 ? ` _(${r.parentL1.weightage}% weight)_` : "";
          lines.push("");
          lines.push(`### ${r.parentL1?.title || "(untitled L1)"}${w}`);
          pendingHeader = true;
        }
        if (pendingHeader) emitTableHeader();
        const expected = mdEscape(formatExpected(r.spec));
        const achieved = mdEscape(r.reading?.value || "—");
        const status = r.reading?.statusLabel || "—";
        const title = mdEscape(r.goal?.title || "(untitled L2)");
        lines.push(`| ${title} | ${expected} | ${achieved} | ${status} |`);
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `_Generated by eSpace/DevHub · ${new Date().toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    })} · Source: your logged goal evidence_`,
  );

  return lines.join("\n");
}

/**
 * Escape pipe characters so they don't break markdown table rows.
 * Anything else is left alone — the rest of the markdown shape is
 * fine because cell content is short.
 */
function mdEscape(s) {
  return String(s ?? "").replace(/\|/g, "\\|");
}

export function downloadMarkdown(filename, content) {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function rangeToLabel(range) {
  const now = new Date();
  const d = new Date(now);
  if (range === "30d") d.setDate(d.getDate() - 30);
  if (range === "90d") d.setDate(d.getDate() - 90);
  if (range === "q1") {
    return `Q1 ${now.getFullYear()} · Jan 1 — Mar 31`;
  }
  if (range === "custom") return "Custom";
  return `${d.toLocaleDateString("en-US", { month: "short", day: "numeric" })} — ${now.toLocaleDateString(
    "en-US",
    { month: "short", day: "numeric", year: "numeric" },
  )}`;
}
