/**
 * Pure rendering — builds the Markdown string for the evidence export.
 * Separated from UI so it can be unit-tested and reused for PDF.
 */

import { formatExpected } from "./format-expected";

export function renderMarkdown({
  name,
  team,
  level,
  rangeLabel,
  narrative,
  goalReadings,
  include = { narrative: true, goals: true },
}) {
  const lines = [];
  lines.push(`# ${name ?? "—"} — ${level ?? "Performance review"}`);
  lines.push(`_${team ?? ""} · ${rangeLabel ?? ""}_`);
  lines.push("");

  if (include.narrative && narrative?.trim()) {
    lines.push("## 01 · Summary");
    lines.push(narrative.trim());
    lines.push("");
  }

  if (include.goals && Array.isArray(goalReadings) && goalReadings.length > 0) {
    const l1s = goalReadings.filter((r) => r.level === "L1").length;
    const l2s = goalReadings.filter((r) => r.level === "L2").length;
    lines.push(`## 02 · Performance goals · ${l1s} L1 · ${l2s} L2`);
    // Group L1 → its L2s. Each L2 becomes a per-goal block — what it was set
    // out to achieve → where it landed (+ tier), the grader's assessment (the
    // "how/why"), and the dated proof logged against it (the "when"). Richer
    // than a flat table, which can't hold reasoning + an evidence list.
    let activeL1 = null;
    for (const r of goalReadings) {
      if (r.level === "L1") {
        activeL1 = r;
        const w = r.goal?.weightage > 0 ? ` _(${r.goal.weightage}% weight)_` : "";
        lines.push("");
        lines.push(`### ${r.goal?.title || "(untitled L1)"}${w}`);
        if (r.reading) {
          lines.push("");
          lines.push(`> ${r.reading.value} — _${r.reading.statusLabel}_`);
        }
      } else if (r.level === "L2") {
        if (!activeL1 || activeL1.goal?.id !== r.parentL1?.id) {
          activeL1 = { goal: r.parentL1, level: "L1", reading: null };
          const w =
            r.parentL1?.weightage > 0 ? ` _(${r.parentL1.weightage}% weight)_` : "";
          lines.push("");
          lines.push(`### ${r.parentL1?.title || "(untitled L1)"}${w}`);
        }
        emitGoalBlock(lines, r);
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `_Generated by eSpace/DevHub · ${new Date().toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    })} · Source: your logged goal evidence_`,
  );

  return lines.join("\n");
}

const TIER_SHORT = {
  not_achieved: "Not met",
  achieved: "Achieved",
  over_achieved: "Over-achieved",
  role_model: "Role model",
};

/** Short calendar date for an evidence timestamp — the "when". */
function fmtDate(ts) {
  if (!ts) return "";
  return new Date(ts).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

/**
 * One L2 goal as a markdown block: target → achieved (+ tier), the grader's
 * assessment (the "how/why"), and the dated evidence logged against it (the
 * "when"). `r` is an enriched reading row carrying `verdict` + `evidence`.
 */
function emitGoalBlock(lines, r) {
  const v = r.verdict;
  const graded = v && !v.awaiting && !v.pendingSetup;
  const tier = graded && v.tier ? TIER_SHORT[v.tier] : null;
  const expected = formatExpected(r.spec) || "—";
  const achieved = r.reading?.value || "—";
  const status = r.reading?.statusLabel || "—";

  lines.push("");
  lines.push(`#### ${r.goal?.title || "(untitled L2)"}${tier ? ` — ${tier}` : ""}`);
  lines.push(`- **Target:** ${expected} → **Achieved:** ${achieved} _(${status})_`);
  if (graded && v.reasoning) {
    lines.push(
      `- **Assessment:** ${v.reasoning}${v.confidence === "low" ? " _(low confidence)_" : ""}`,
    );
  }
  const evidence = Array.isArray(r.evidence) ? r.evidence : [];
  if (evidence.length) {
    lines.push(`- **Evidence:**`);
    for (const ev of evidence) {
      lines.push(`  - ${fmtDate(ev.ts)} — ${ev.text}`);
    }
  }
}

export function downloadMarkdown(filename, content) {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function rangeToLabel(range) {
  const now = new Date();
  const d = new Date(now);
  if (range === "30d") d.setDate(d.getDate() - 30);
  if (range === "90d") d.setDate(d.getDate() - 90);
  if (range === "q1") {
    return `Q1 ${now.getFullYear()} · Jan 1 — Mar 31`;
  }
  if (range === "custom") return "Custom";
  return `${d.toLocaleDateString("en-US", { month: "short", day: "numeric" })} — ${now.toLocaleDateString(
    "en-US",
    { month: "short", day: "numeric", year: "numeric" },
  )}`;
}
